### ISSUE TITLE
SimulatorControl Verticle thread is blocking when Responder Service is unavailable or throws error

### ISSUE THREAD

**Issue by btison** [NAPS-emergency-response-project/responder-simulator#1]
In the logs:
```2019-05-04 10:20:50 ERROR SimulationControl:343 - Something went wrong Search domain query failed. Original hostname: 'responder-service.naps-emergency-response.svc' failed to resolve 'responder-service.naps-emergency-response.svc.naps-emergency-response.svc.cluster.local' after 2 queries 
2019-05-04 10:21:45 WARN  BlockedThreadChecker:55 - Thread Thread[vert.x-worker-thread-13,5,main] has been blocked for 60008 ms, time limit is 60000 ms
io.vertx.core.VertxException: Thread blocked
	at sun.misc.Unsafe.park(Native Method)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.CompletableFuture$Signaller.block(CompletableFuture.java:1693)
	at java.util.concurrent.ForkJoinPool.managedBlock(ForkJoinPool.java:3323)
	at java.util.concurrent.CompletableFuture.waitingGet(CompletableFuture.java:1729)
	at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
	at io.reactivex.internal.operators.flowable.FlowableFromFuture.subscribeActual(FlowableFromFuture.java:42)
	at io.reactivex.Flowable.subscribe(Flowable.java:14636)
	at io.reactivex.internal.operators.flowable.FlowableSingleSingle.subscribeActual(FlowableSingleSingle.java:39)
	at io.reactivex.Single.subscribe(Single.java:3495)
	at io.reactivex.internal.operators.single.SingleDoOnError.subscribeActual(SingleDoOnError.java:35)
	at io.reactivex.Single.subscribe(Single.java:3495)
	at io.reactivex.internal.operators.single.SingleDoOnSuccess.subscribeActual(SingleDoOnSuccess.java:35)
	at io.reactivex.Single.subscribe(Single.java:3495)
	at io.reactivex.Single.subscribe(Single.java:3481)
	at io.reactivex.Single.subscribe(Single.java:3402)
	at com.redhat.cajun.navy.responder.simulator.SimulationControl.getResponder(SimulationControl.java:318)
	at com.redhat.cajun.navy.responder.simulator.SimulationControl.lambda$addResponder$5(SimulationControl.java:206)
	at com.redhat.cajun.navy.responder.simulator.SimulationControl$$Lambda$151/1626300997.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.lambda$executeBlocking$2(ContextImpl.java:272)
	at io.vertx.core.impl.ContextImpl$$Lambda$48/1780132728.run(Unknown Source)
	at io.vertx.core.impl.TaskQueue.run(TaskQueue.java:76)
	at io.vertx.core.impl.TaskQueue$$Lambda$19/764372388.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)
```
The issue seems to be that in the `SimulationControl.getResponder` method the `CompletableFuture` is never completed in case of error.

```    protected CompletableFuture<Boolean> getResponder(String id){

        CompletableFuture<Boolean> request = new CompletableFuture<>();
        client.get(port, host, uri+id)
                .send(ar -> {
                    if (ar.succeeded()) {
                        // Obtain response
                        HttpResponse<Buffer> response = ar.result();
                        JsonObject obj = response.bodyAsJsonObject();
                        logger.debug("Received response with status code" + response.statusCode());
                        logger.info("ResponderService: " + obj);
                        request.complete(obj.getBoolean("person"));
                    } else {
                        logger.error("Something went wrong " + ar.cause().getMessage());
                    }
                });

            return request;


    }
```

**Comment by sshaaf** [comment]
Close Fixed
